### ISSUE TITLE
when I click on Certificate Details modal looks like this. 

### ISSUE THREAD

**Issue by vayuzpriya** [Anupriyabanger/Bee-Recruiter#1406] opened 2023-11-09 08:47 UTC
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/81085431/e2473b70-f9fc-4384-8973-ba77201edd46)

**Comment by vinayak-vayuz** [comment] 2024-03-01 11:18
Duplicate of #891

**Closed as completed** 2024-03-01 11:18 UTC
Labels: duplicate, UI, jobseeker, web
