### ISSUE TITLE
CV management > tag color on status

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/Bee-Recruiter#480] opened 2023-06-22 08:20 UTC

**Comment by naveesha-vayuz** [comment] 2023-06-22 08:23
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/121479721/0adda792-bc19-43aa-8f4c-2b35212867c0)

**Comment by vinayak-vayuz** [comment] 2023-07-28 11:02
Closing it as It's a duplicate of #546 issue.

**Closed as completed by vinayak-vayuz** 2023-07-28 11:02 UTC
Labels: duplicate, UI, web, Employer
